## Tuto

In [3]:
import gym

from stable_baselines3 import A2C

env = gym.make('CartPole-v1')

model = A2C('MlpPolicy', env, verbose=1)
model.learn(total_timesteps=10000)

obs = env.reset()
for i in range(1000):
    action, _state = model.predict(obs, deterministic=True)
    obs, reward, done, info = env.step(action)
    env.render()
    if done:
        obs = env.reset()

Using cpu device
Wrapping the env with a `Monitor` wrapper
Wrapping the env in a DummyVecEnv.
------------------------------------
| rollout/              |          |
|    ep_len_mean        | 27.4     |
|    ep_rew_mean        | 27.4     |
| time/                 |          |
|    fps                | 3282     |
|    iterations         | 100      |
|    time_elapsed       | 0        |
|    total_timesteps    | 500      |
| train/                |          |
|    entropy_loss       | -0.667   |
|    explained_variance | -0.487   |
|    learning_rate      | 0.0007   |
|    n_updates          | 99       |
|    policy_loss        | -3.83    |
|    value_loss         | 47.3     |
------------------------------------
------------------------------------
| rollout/              |          |
|    ep_len_mean        | 22.1     |
|    ep_rew_mean        | 22.1     |
| time/                 |          |
|    fps                | 3230     |
|    iterations         | 200      |
|    time_elapsed 

------------------------------------
| rollout/              |          |
|    ep_len_mean        | 29.7     |
|    ep_rew_mean        | 29.7     |
| time/                 |          |
|    fps                | 3252     |
|    iterations         | 1400     |
|    time_elapsed       | 2        |
|    total_timesteps    | 7000     |
| train/                |          |
|    entropy_loss       | -0.381   |
|    explained_variance | 9.06e-05 |
|    learning_rate      | 0.0007   |
|    n_updates          | 1399     |
|    policy_loss        | 1.81     |
|    value_loss         | 2.66     |
------------------------------------
------------------------------------
| rollout/              |          |
|    ep_len_mean        | 31.7     |
|    ep_rew_mean        | 31.7     |
| time/                 |          |
|    fps                | 3254     |
|    iterations         | 1500     |
|    time_elapsed       | 2        |
|    total_timesteps    | 7500     |
| train/                |          |
|

KeyboardInterrupt: 

In [2]:
from stable_baselines3 import A2C

model = A2C('MlpPolicy', 'CartPole-v1').learn(10000)

## Setup

In [9]:
import numpy as np

import gym
from gym import spaces

from stable_baselines.common.env_checker import check_env
from stable_baselines.common.evaluation import evaluate_policy
from stable_baselines.common.policies import MlpPolicy

from stable_baselines.common.policies import MlpPolicy, MlpLstmPolicy, MlpLnLstmPolicy
from stable_baselines.common import make_vec_env
from stable_baselines import ACER

ModuleNotFoundError: No module named 'tensorflow.contrib'

## Environement

In [ ]:
grid_size = 5
n_actions = grid_size * grid_size

In [ ]:
class CustomEnv(gym.Env):
  """Custom Environment that follows gym interface"""
  metadata = {'render.modes': ['human']}

    def __init__(self, arg1, arg2, ...):
        super(CustomEnv, self).__init__()
        # Define action and observation space
        # They must be gym.spaces objects
        # Example when using discrete actions:
        self.action_space = spaces.Discrete(N_DISCRETE_ACTIONS)
        # Example for using image as input:
        self.observation_space = spaces.Box(low=0, high=255,
                                        shape=(HEIGHT, WIDTH, N_CHANNELS), dtype=np.uint8)

    def step(self, action):
        pass
        return observation
    
    
    def reset(self):
        pass
        ©  # reward, done, info can't be included
    
    
    def render(self, mode='human'):
        pass
        
        
    def close (self):
        pass
        

In [ ]:
class IArchitectEnv(gym.Env):
    
    metadata = {'render.modes': ['human']}
    position = [(0,0),(0,1),(0,2),(2,0),(2,1),(2,2),(2,0),(2,1),(2,2)]
    score = 0
    
    def __init__(self,verbose=False):
        
        self.verbose = verbose
        self.state = np.zeros((3,3),dtype=np.int32)
        self.action_space = spaces.Discrete(9)
        self.observation_space = spaces.Box(low=0, high=255, shape=(3,3), dtype=np.uint8)
        
        self.done = False
        self.score = 0
        self.win = 10
        self.failed = -10
        self.reward = 1
        
        self.x = 0
        self.y = 0

        
    def reset(self):
        
        self.state = np.zeros((3,3),dtype=np.int32)
        self.done = False
        self.score = 0
        
        return self.state


    def step(self, action):
        
        position = [(0,0),(0,1),(0,2),(2,0),(2,1),(2,2),(2,0),(2,1),(2,2)]
        
        if self.done:
            return self.reset()
        
        if self.verbose:
            print(self.state,action)

        self.x, self.y = position[action]
        reward = self.reward
        
        if self.state[self.x,self.y]==1:
            reward = self.failed
            self.done = True

        self.state[self.x,self.y] = 1

        if self.state.sum()==self.state.shape[0]:
            self.done = True
            reward = self.win
        
        #score += reward
        info = {}#{f'Score:{score}'}
        
        if self.verbose:
            print(self.state, reward, self.score)
            
        return self.state, reward, self.done, info

    
    def render(self, mode='console'):
        if mode != 'console':
            raise NotImplementedError()

        print(self.state, action, self.x, self.y)
        print(self.reward, self.done)
        
    def close(self):
        pass

In [ ]:
class GoLeftEnv(gym.Env):
    """
    Custom Environment that follows gym interface.
    This is a simple env where the agent must learn to go always left. 
    """
    # Because of google colab, we cannot implement the GUI ('human' render mode)
    metadata = {'render.modes': ['console']}
    # Define constants for clearer code
    LEFT = 0
    RIGHT = 1

    def __init__(self, grid_size=10):
        super(GoLeftEnv, self).__init__()

        self.grid_size = grid_size
        self.agent_pos = grid_size - 1
        self.action_space = spaces.Discrete(n_actions)
        self.observation_space = spaces.Box(low=0, high=self.grid_size,
                                        shape=(5,5), dtype=np.int32)

    def reset(self):
        """
        Important: the observation must be a numpy array
        :return: (np.array) 
        """
        # Initialize the agent at the right of the grid
        self.agent_pos = self.grid_size - 1
        # here we convert to float32 to make it more general (in case we want to use continuous actions)
        return np.array([self.agent_pos]).astype(np.float32)

    def step(self, action):
        
        if action == self.LEFT:
            self.agent_pos -= 1
        elif action == self.RIGHT:
            self.agent_pos += 1
        else:
            raise ValueError("Received invalid action={} which is not part of the action space".format(action))

        # Account for the boundaries of the grid
        self.agent_pos = np.clip(self.agent_pos, 0, self.grid_size)

        # Are we at the left of the grid?
        done = bool(self.agent_pos == 0)

        # Null reward everywhere except when reaching the goal (left of the grid)
        reward = 1 if self.agent_pos == 0 else 0

        # Optionally we can pass additional info, we are not using that for now
        info = {}

        return np.array([self.agent_pos]).astype(np.float32), reward, done, info

    
    def render(self, mode='console'):
        if mode != 'console':
            raise NotImplementedError()
        # agent is represented as a cross, rest as a dot
        print("." * self.agent_pos, end="")
        print("x", end="")
        print("." * (self.grid_size - self.agent_pos))
        print(reward)

    def close(self):
        pass

## Test Random Environment

In [ ]:
env = IArchitectEnv()
check_env(env, warn=True)

In [64]:
#environment = IArchitectEnv()
#env = gym.make(environment)

In [65]:
episodes = 10

for episode in range(1, episodes+1):
    state = env.reset()
    done = False
    score = 0 
    
    while not done:
        env.render()
        action = env.action_space.sample()
        n_state, reward, done, info = env.step(action)
        score+=reward
    print('Episode:{} Score:{}'.format(episode, score))

env.close()

[[0 0 0]
 [0 0 0]
 [0 0 0]] 4 2 1
1 False
[[0 0 0]
 [0 0 0]
 [1 0 0]] 6 2 0
1 False
[[0 0 0]
 [0 0 0]
 [1 0 1]] 5 2 2
1 False
Episode:1 Score:12
[[0 0 0]
 [0 0 0]
 [0 0 0]] 2 0 2
1 False
[[0 0 0]
 [0 0 0]
 [0 0 1]] 5 2 2
1 False
Episode:2 Score:-9
[[0 0 0]
 [0 0 0]
 [0 0 0]] 5 2 2
1 False
[[0 0 0]
 [0 0 0]
 [0 0 1]] 8 2 2
1 False
[[1 0 0]
 [0 0 0]
 [0 0 1]] 0 0 0
1 False
Episode:3 Score:12
[[0 0 0]
 [0 0 0]
 [0 0 0]] 3 2 0
1 False
[[0 0 0]
 [0 0 0]
 [0 1 0]] 7 2 1
1 False
[[0 0 0]
 [0 0 0]
 [1 1 0]] 3 2 0
1 False
Episode:4 Score:12
[[0 0 0]
 [0 0 0]
 [0 0 0]] 2 0 2
1 False
[[0 0 0]
 [0 0 0]
 [0 0 1]] 5 2 2
1 False
[[0 0 0]
 [0 0 0]
 [0 1 1]] 4 2 1
1 False
Episode:5 Score:12
[[0 0 0]
 [0 0 0]
 [0 0 0]] 6 2 0
1 False
[[0 0 1]
 [0 0 0]
 [0 0 0]] 2 0 2
1 False
[[0 0 1]
 [0 0 0]
 [0 0 1]] 8 2 2
1 False
Episode:6 Score:12
[[0 0 0]
 [0 0 0]
 [0 0 0]] 1 0 1
1 False
[[0 0 0]
 [0 0 0]
 [1 0 0]] 6 2 0
1 False
[[0 0 0]
 [0 0 0]
 [1 1 0]] 7 2 1
1 False
Episode:7 Score:-8
[[0 0 0]
 [0 0 0]
 [0 0 0]]

## Build and Train the Model

In [68]:
model = ACER('MlpPolicy', env, verbose=1)

NameError: name 'ACER' is not defined

In [ ]:
model.learn(total_timesteps=100000)

## Save and Test the Model

In [ ]:
# Delete
evaluate_policy(model, env, n_eval_episodes=10, render=True)
env.close()

In [ ]:
# Save the model
model.save("ACER_model")

In [2]:
# Delete the model
del model

In [ ]:
# Load the model
model = ACER.load("ACER_model", env=env)

In [ ]:
# Reset and test the model
obs = env.reset()
while True:
    action, _states = model.predict(obs)
    obs, rewards, done, info = env.step(action)
    env.render()